filebeat.inputs:
  - type: docker
    paths:
      - '/var/lib/docker/containers/*/*.log'
    containers:
      ids: '*'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.elasticsearch:
  hosts: ["{{ container_prefix }}_elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false